version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .
     # deploy the image
     - run: |         
         docker login --username=arvindkpal@hotmail.com --password=iFM*#254 registry.heroku.com
         docker tag aspnetapp registry.heroku.com/aspcore-angular-test/web
         docker push registry.heroku.com/aspcore-angular-test/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a aspcore-angular-test